sudo: required

services:
  - docker

before_install:
  - docker build -t samcamcode/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true samcamcode/react-test npm test

after_success:
  - docker build -t samcamcode/multi-client ./client
  - docker build -t samcamcode/multi-nginx ./nginx
  - docker build -t samcamcode/multi-server ./server
  - docker build -t samcamcode/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push samcamcode/multi-client
  - docker push samcamcode/multi-nginx
  - docker push samcamcode/multi-server
  - docker push samcamcode/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-121852036586
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
